Areas/Account/Controllers/ClaimsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AspMvcAuth.Models;
using System.Security.Claims;
namespace AspMvcAuth.Areas.Account.Controllers
{
	[Authorize]
	public class ClaimsController : Controller
	{
		[Route("{area}/{controller}")]
		public IActionResult Index()
		{
			return View(User?.Claims);
		}

		[Route("{area}/{controller}/{action}")]
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[Route("{area}/{controller}/{action}")]
		[HttpPost]
		public async Task<IActionResult> Create([FromServices]UserManager<ApplicationUser> users, string claimType, string claimValue)
		{
			var user = await users.GetUserAsync(HttpContext.User);
			Claim claim = new(claimType, claimValue, ClaimValueTypes.String);
			IdentityResult result = await users.AddClaimAsync(user, claim);

			if (result.Succeeded)
				return LocalRedirect("/account/claims");
			else
				return BadRequest(result);
		}

		[HttpPost]
		[Route("{area}/{controller}/{action}")]
		public async Task<IActionResult> Delete([FromServices] UserManager<ApplicationUser> users, string claimValues)
		{
			var user = await users.GetUserAsync(HttpContext.User);

			string[] claimValuesArray = claimValues.Split(";");
			string claimType = claimValuesArray[0];
			string claimValue = claimValuesArray[1]; 
			string claimIssuer = claimValuesArray[2];

			Claim claim = User.Claims.Where(x => x.Type == claimType && x.Value == claimValue && x.Issuer == claimIssuer).FirstOrDefault();

			IdentityResult result = await users.RemoveClaimAsync(user, claim);

			if (result.Succeeded)
				return LocalRedirect("/account/claims");
			else
				return BadRequest(result);
		}
	}
}

Views/Shared/AccessDanied.cshtml
<h2 class="bg-danger p-1 text-white">Вам запрещен доступ к этой странице</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspMvcAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspMvcAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspMvcAuth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Account" asp-controller="Role" asp-action="Role">Управление ролями</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Account" asp-controller="Claims" asp-action="Index">Утверждения</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspMvcAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>